site_name: The Johnson Lab Wiki
site_description: "Collaborative Knowledge Hub for the W. Evan Johnson Lab at Rutgers University"
site_author: "Johnson Lab Members"

repo_url: https://github.com/wejlab
repo_name: 'GitHub'

nav:
    - Home: 'index.md'
    - Lab Resources:
        - Code Review:
            - 'code_review/code_review_overview.md'
            - 'code_review/general_code_review.md'
            - 'code_review/informal_code_review.md'
            - 'code_review/lab_meeting_code_review.md'
            - 'code_review/manuscript_code_review.md'
            - 'code_review/tips_code_review.md'
        - 'lab_meeting.md'
        - 'protected_time.md'
        - 'slack.md'
        - 'lab_retreat_2025.md'
        - 'annual_checkin.md'
        - 'grant_timelines.md'
        - 'grant_outline.md'
        - 'manuscript_checklist.md'
    - Learning Resources:
        - 'learning_resources/quicklinks.md'
        - 'learning_resources/git_expert.md'
        - 'learning_resources/r_packages.md'
        - 'learning_resources/sharing_r_packages.md'
        - 'learning_resources/metascope.md'
    - Wiki Ideas: 'wiki_ideas.md'

extra_css:
- stylesheets/extra.css
theme:
    name: windmill
    search_index_only: true
    include_search_page: true
